### PR TITLE
General cleanups of Rust code, port over timer interrupt fixes

### PR DESCRIPTION
**Pull request by archshift**
Ideally, these commits should cleanly build upon each other to make following these cleanups somewhat self-explanatory.

### CODE REVIEW

**Comment by archshift** [comment]
Pending #60 to merge this

**Comment by dayeol** [comment]
The trap handling has been updated since this PR.

**Comment by archshift** [comment]
Should be good to go!

**Comment by dayeol** [comment]
Looks good to me.
For the record, this PR contains changes made in #61

**Pull request merged**
